{% set name = "fiesta-pkg" %}
{% set version = "0.1.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  path: ..

requirements:
  host:
    - gfortran
    - python
    - setuptools >=49.6.0
    - numpy >=1.20
    - scipy >=1.6.2
    - matplotlib >=3.4.1
    - healpy >=1.14
    - magpie-pkg >= 0.3
  run:
    - python
    - setuptools >=49.6.0
    - numpy >=1.20
    - scipy >=1.6.2
    - matplotlib >=3.4.1
    - healpy >=1.14
    - magpie-pkg >= 0.3

test:
  imports:
    - fiesta

about:
  home: "https://fiesta-doc.readthedocs.io/"
  license: MIT
  summary: "FIeld ESTimAtor"
